version_name = 'v37'
OBSTACLE_DENSITY = 1.0
LR = 1e-3
MIN_LR = 1e-5
PATIENCE = 2
OPTIMIZER = 'SGD'
DECAY_EXPLORE_RATE = 0.97
DECAY_NOMINAL_RATE = 0.8
MIN_EXPLORE_EPS = 0.
MAX_EXPLORE_EPS = 0.5
POTENTIAL_OBS = True
PREFERENCE_OBS = True
TRAIN_ON_HARD = False
VARIABLE_AGENT = False
CBUF_BEFORE_RELABEL = True
PER_STEP_EXPLORE = False
CBUF_ONLY_BOUNDARY = True

N_TRAJ = N_EPOCH = 1000000
N_CBUF = 300

NUM_AGENTS = 8
MAP_SIZE = 4

n_candidates = 2000
BATCH = 1024
N_ITER = 100
N_TRAJ_PER_EPOCH = 10
N_BUFFER = 20
N_EVALUATE = 100
N_VALID = 100
N_WARMUP = 100
N_DATASET = 10
N_VALID_DATASET = 20
THRESHOLD = 1.5e-2
HIDDEN_SIZE = 128
RELABEL = True
CYCLIC = False
DECAY_RELABEL = False
USE_SCHEDULER = True
SAVE_GIF = False