version_name = 'v108'

ENV_CONFIG = {
    'num_agents': 8,
    'SIZE': (4,4),
    'agent_top_k': 6,
    'obstacle_top_k': 2,
    'PROB': (0.,1.0),
    'simple': False,
}

FIX_ENV = False

LR = 3e-4
PATIENCE = 2
DECAY_EXPLORE_RATE = 0.9
DECAY_NOMINAL_RATE = 0.
MIN_EXPLORE_EPS = 0.01
MAX_EXPLORE_EPS = 1.0
POTENTIAL_OBS = False
TRAIN_ON_HARD = True
VARIABLE_AGENT = False
CBUF_BEFORE_RELABEL = True
REFINE_EPS = 1.0
RELABEL_ONLY_AGENT = False
ALL_LIE = True
ONLY_BOUNDARY = False
DANGER_THRESHOLD = 0
CLIP_NORM = True

MODEL = 'OriginGNNv6'


PE_DIM = 40
N_TRAJ = N_EPOCH = 1000000000
N_BUFFER = 10000
N_CBUF = 0
MAX_VISIT_TIME = 1000

POLYAK = 0.99
SPATIAL_PROP = False
n_candidates = 200
BATCH = 128
N_ITER = 50
N_TRAJ_PER_EPOCH = 10
N_EVALUATE = 100
N_VALID = 100
N_WARMUP = 0
N_DATASET = 10
N_VALID_DATASET = 50
THRESHOLD = 1e-2
HIDDEN_SIZE = 256
RELABEL = True
EXPLORE_WAY = 'exponential'
NOMINAL_WAY = 'exponential'
DECAY_RELABEL = True
USE_SCHEDULER = True
OPTIMIZER = 'Adam'
SAVE_GIF = False